export const GET_CATEGORY_BEGIN = 'GET_CATEGORY_BEGIN';

export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';

export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR';


export const GET_COURSE_BEGIN = 'GET_COURSE_BEGIN';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_ERROR = 'GET_COURSE_ERROR';


export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';

export const ADD_TO_CART = 'ADD_TO_CART';

